name: Build SteamClip for Linux and Windows

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            script: steamclip.py
            output: steamclip
          - os: windows-latest
            script: steamclipWINDOWS.py
            output: steamclip.exe
            icon: SteamClip.ico

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            pyinstaller --onefile --icon "${{ matrix.icon }}" "${{ matrix.script }}"
          else
            pyinstaller --onefile "${{ matrix.script }}"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: dist/${{ matrix.output }}
